MVCProjectCamp/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjectCamp.Controllers
{
    public class AboutController : Controller
    {
        AboutManager abm = new AboutManager(new EFAboutDal());
        // GET: About
        public ActionResult Index()
        {
            var aboutValues = abm.GetList();
            return View(aboutValues);
        }
        [HttpGet]
        public ActionResult AddAbout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAbout(About p)
        {
            abm.AboutAddBl(p);
            return RedirectToAction("Index");  
        }

        public PartialViewResult AboutPartial()
        {
            return PartialView();
        }
    }
}

MVCProjectCamp/Views/About/AboutPartial.cshtml
<button class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    New About Text Input
</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Text Input</h2>
            </div>
            <form method="post" action="/About/AddAbout">
                <div class="modal-body">
                    <label>About Text 1</label>
                    <input type="text" name="AboutDetails1" class="form-control" />
                    <br />
                    <label>About Text 2</label>
                    <input type="text" name="AboutDetails2" class="form-control" />
                    <br />
                    <label>About Image 1</label>
                    <input type="text" name="AboutImage1" class="form-control" />
                    <br />
                    <label>About Image 2</label>
                    <input type="text" name="AboutImage2" class="form-control" />
                    <br />
                    <button class="btn btn-info">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

MVCProjectCamp/Views/About/Index.cshtml
@using EntityLayer.Concrete
@model List<About>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>About Data List</h2>
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>About Heading</th>
            <th>Make Active</th>
            <th>Make Passive</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.AboutId</td>
                <td>Başlık</td>
                <td><a href="#" class="btn btn-warning">Make Active</a></td>
                <td><a href="#" class="btn btn-danger">Make Passive</a></td>
            </tr>
        }
    </table>

@Html.Action("AboutPartial","About")