MVCProjectCamp/Controllers/ContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjectCamp.Controllers
{
    public class ContentController : Controller
    {
        // GET: Content
        ContentManager cm = new ContentManager(new EFContentDal());
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetAllContent(string p)
        {
            var values = cm.GetList(p);
            return View(values);
            //var values = c.Contents.ToList();        
        }
        public ActionResult ContentByHeading(int id)
        {
            var contentValues = cm.GetListByHeadingID(id);
            return View(contentValues);                                 
        }
    }
}

MVCProjectCamp/Views/Content/ContentByHeading.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MMM-yyyy"))</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Writer.WriterName @item.Writer.WriterSurname</a></h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            }
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MVCProjectCamp/Views/Content/GetAllContent.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "GetAllContent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using (Html.BeginForm("GetAllContent","Content",FormMethod.Post))
            {
                <p>
                    Enter a word you looking for : @Html.TextBox("p")
                    <input type="submit" value="Search" />
                </p>
            }

@foreach (var item in Model)
{
    <p>@item.ContentValue</p>
}