MVCProjectCamp/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjectCamp.Controllers
{
    public class WriterPanelContentController : Controller
    {
        ContentManager cm = new ContentManager(new EFContentDal());
        Context c = new Context();
        // GET: WriterPanelContent
        public ActionResult MyContent(string p)
        {      
            p = (string)Session["WriterMail"];
            var writer_ID_Info = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault(); 
            var contentValues = cm.GetListByWriter(writer_ID_Info);
            return View(contentValues);    
        }
        [HttpGet]
        public ActionResult AddContent(int id)
        {
            ViewBag.d = id;
            return View();
        }
        [HttpPost]
        public ActionResult AddContent(Content p)
        {
            string mail = (string)Session["WriterMail"];
            var writer_ID_Info = c.Writers.Where(x => x.WriterMail == mail).Select(y => y.WriterID).FirstOrDefault();
            p.ContentDate = DateTime.Parse(DateTime.Now.ToLongDateString());
            p.WriterID = writer_ID_Info;
            p.ContentStatus = true;
            cm.ContentAddBl(p);
            return RedirectToAction("MyContent");
        }
        public ActionResult ToDoList()
        {
            return View();
        }

    }
}

MVCProjectCamp/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<h2>Keep Writing</h2>
<br />
@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))
{
    <div class="form-group">
        <input type="hidden" name="HeadingID" value="@ViewBag.d" />
        @Html.Label("Write your content")
        @Html.TextAreaFor(x => x.ContentValue,10,30, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ContentValue)
        <br />
        <button class="btn btn-info">Save</button>
    </div>
}

MVCProjectCamp/Views/WriterPanelContent/MyContent.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MMM-yyyy"))</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a></h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            }
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MVCProjectCamp/Views/WriterPanelContent/ToDoList.cshtml
@{
    ViewBag.Title = "ToDoList";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<p>#1 Profilim</p>
<p>#2 Paging for All Headings</p>
<p>#3 Section for Messaging</p>
<p>#4 Migration of session management to architecture</p>
<p>#5 Use of Token</p>